### ISSUE TITLE
[iOS] The problem with fields of type radio

### ISSUE THREAD

**Issue by mrmlnc** [jamiewilson/corpus#13]
If you specify the `border-radius` property for all fields:

``` css
input,
select,
textarea,
fieldset {
  font-family: inherit;
  font-size: 1rem;
  border: none;
  border-radius: 0;        <--- this property
}
```

then in iOS, fields of type radio lose their appearance. A screenshot on iOS 9.2:

![image](https://cloud.githubusercontent.com/assets/7034281/11394610/386ac3a2-9377-11e5-8aa0-aa72bd1de879.png)
